# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rtmvnormcpp <- function(mean, sigma, blc, lower, upper, init, burn) {
    .Call(`_IIGpkg_rtmvnormcpp`, mean, sigma, blc, lower, upper, init, burn)
}

norm_rej <- function(a, b) {
    .Call(`_IIGpkg_norm_rej`, a, b)
}

unif_rej <- function(a, b) {
    .Call(`_IIGpkg_unif_rej`, a, b)
}

halfnorm_rej <- function(a, b) {
    .Call(`_IIGpkg_halfnorm_rej`, a, b)
}

exp_rej <- function(a, b) {
    .Call(`_IIGpkg_exp_rej`, a, b)
}

rtnormcpp <- function(mean, sd, lower, upper) {
    .Call(`_IIGpkg_rtnormcpp`, mean, sd, lower, upper)
}

#' Sum in the inverse of the posterior variance for loadings/partial effects
#'
#' @param invOmega0 inverse prior matrix
#' @param availableObs available observations
#' @param id_f `integer` (sequence); index for selection of correct factors
#' @param fPost backward sampled states (FFBS output)
#' @param w_regs regressor matrix
#' @param Viarray VCOV array (npara x npara x TT) of cross-sectional unit i
#'
#' @return summation of kronecker products of appropriate dimension
#'
compute_B_mean_cpp <- function(Omega, invOmega_B0_D0, availableObs, selectR, fPost, w_regs, yiObs, Viarray) {
    .Call(`_IIGpkg_compute_B_mean_cpp`, Omega, invOmega_B0_D0, availableObs, selectR, fPost, w_regs, yiObs, Viarray)
}

#' Sum in the inverse of the posterior variance for loadings/partial effects
#'
#' @param invOmega0 inverse prior matrix
#' @param availableObs available observations
#' @param id_f `integer` (sequence); index for selection of correct factors
#' @param fPost backward sampled states (FFBS output)
#' @param w_regs regressor matrix
#' @param Viarray VCOV array (npara x npara x TT) of cross-sectional unit i
#'
#' @return summation of kronecker products of appropriate dimension
#'
compute_Omega1_cpp <- function(invOmega0, availableObs, selectR, fPost, w_regs, Viarray) {
    .Call(`_IIGpkg_compute_Omega1_cpp`, invOmega0, availableObs, selectR, fPost, w_regs, Viarray)
}

#' Sum in the inverse of the posterior variance for loadings/partial effects
#'
#' @inheritParams compute_Omega1_cpp
#'
#' @return summation of kronecker products of appropriate dimension
#'
sum_ff_kron_v <- function(availableObs, fPost, w_regs, Viarray) {
    .Call(`_IIGpkg_sum_ff_kron_v`, availableObs, fPost, w_regs, Viarray)
}

#' Sum in the inverse of the posterior variance for loadings/partial effects
#'
#' @inheritParams compute_Omega1_cpp
#'
#' @return summation of kronecker products of appropriate dimension
#'
sum_f_y_v <- function(availableObs, fPost, w_regs, yiObs, Viarray) {
    .Call(`_IIGpkg_sum_f_y_v`, availableObs, fPost, w_regs, yiObs, Viarray)
}

