# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Sum in the inverse of the posterior variance for loadings/partial effects
#'
#' @param availableObs available observations
#' @param id_f `integer` (sequence); index for selection of correct factors
#' @param fPost backward sampled states (FFBS output)
#' @param w_regs 
#' @param Viarray VCOV array (npara x npara x TT) of cross-sectional unit i
#'
#' @return summation of kronecker products of appropriate dimension
#'
sum_ff_kron_v <- function(availableObs, fPost, w_regs, Viarray) {
    .Call(`_IIGpkg_sum_ff_kron_v`, availableObs, fPost, w_regs, Viarray)
}

